### ISSUE TITLE
Request for Re-uploading the Wikipedia_bd.zip Dataset

### ISSUE THREAD

**Issue by adekang** [Fsoft-AIC/NeuroMax#1]
I hope this message finds you well.

currently, I am working on calculating topic coherence using Wikipedia_bd.zip dataset. However, due to restrictions in China, I am unable to access or download the file. I kindly request if it would be possible for you to re-upload the dataset or provide an alternative means of access (e.g., email or a mirror link).

best regards,
adekang

**Comment by phamduytung2002** [comment]
Hi @adekang,

Thank you for reaching out. I understand your difficulties in accessing the Wikipedia_bd.zip dataset. However, I’d like to clarify that I am not the author of this dataset and am unsure about its licensing terms or permissions for redistribution.

To address this properly, I recommend contacting the original author directly, as they would be the best source for clarifications regarding access and licensing. For more details, you can refer to the original repository here: https://github.com/dice-group/Palmetto .

Thank you for your understanding.

Best regards,
phamduytung2002
